### PR TITLE
refactor utils with pylint

### LINKED ISSUE #666: Easy-to-fix pylint messages in `probnum.utils`
**Context:** 
There is ongoing work on refactoring `probnum` to comply with the desired pylint configuration. See #523 for context.
Many of those refactorings should be very simple to resolve.

**Details:**
For the `probnum.utils` subpackage, these are
- [ ] `line-too-long` (some docstrings have too long lines)
- [ ] `no-else-return`
- [ ] `else-if-used`

Once a message has been resolved, please remove the explicit pylint-ignore on the bottom of the `tox.ini` file.

**Some notes, if you would like to take this on:**
* Have a look at the contribution guide before opening a pull request.
* Please strongly consider resolving each message in a separate pull request. This makes the reviews go more smoothly.

### PR DESCRIPTION
**Pull request by akapoor13**
# In a Nutshell
Fix pylint messages in `probnum.utils`

# Detailed Description
Refactors `probnum.utils` to comply with pylint `line-too-long`, `no-else-return` and `else-if-used`. 

# Related Issues
Closes #666

### CODE REVIEW

**Review by pnkraemer — APPROVED** [review]
Thanks!

**Comment by akapoor13** [comment]
failing black CICD pipeline because of `ImportError: cannot import name '_unicodefun' from 'click' ` in `black` src file

**Comment by JonathanWenger** [comment]
> ImportError: cannot import name '_unicodefun' from 'click'

Possibly related issue: https://github.com/psf/black/issues/2634

**Comment by pnkraemer** [comment]
Hex @akapoor13, it seems that due to the other pylint-PRs being merged more quickly than this one, merge conflicts were created. Please ping me once they are resolved and I will make sure to merge the PR swiftly :)

**Comment by akapoor13** [comment]
Hey @pnkraemer  think we're good to go now

**Pull request merged**
