### PR TITLE
Website Navigation Bar Update

### PR DESCRIPTION
**Pull request by JonathanWenger**
# In a Nutshell
Renames the navigation option on the landing page from "Research" to "Probabilistic Numerics".

### CODE REVIEW

**Comment by philipphennig** [comment]
Thanks! As requested by Mike.

**Review by mmahsereci — APPROVED** [review]

**Comment by philipphennig** [comment]
Looks good to me. 

I get an error message from `dot` when building with `tox`, but can't confirm whether this is just a local problem for me. The change in this PR is definitely good. Thanks!

**Comment by JonathanWenger** [comment]
> Looks good to me.
> 
> I get an error message from `dot` when building with `tox`, but can't confirm whether this is just a local problem for me. The change in this PR is definitely good. Thanks!

Is it possible you are missing `graphviz` (see http://www.probabilistic-numerics.org/en/latest/development/pull_request.html#tox)?
```bash
sudo apt install graphviz
```
This is needed to generate the inheritance diagrams. While `tox` almost reproduces the CI exactly on a local machine for system dependent installation of packages we do not yet have a good solution.

**Comment by philipphennig** [comment]
Thanks for the info. I fixed the issue now (my graphviz install was indeed outdated, I haven’t used it in years). Compiles correctly now.

**Pull request merged**
