### PR TITLE
Touchup for ODE and Filtering Tutorials

### PR DESCRIPTION
**Pull request by JonathanWenger**
# In a Nutshell
Thumbnails and consistent documentation sidebar for the new diffeq and filtering tutorials.

# Detail
ODE and filtering tutorials were missing thumbnails and had sub-headers which appeared in the documentation directory (see below) as opposed to just showing the available Tutorials. This is caused by using multiple top level markdown headers ("#"). 

I also changed some headers to keep things concise and adjusted names according to the styleguide (e.g. usage of ProbNum instead of `probnum`). Header changes are somewhat opinionated so please do let me know if you find them unacceptable. Finally, I `black`ed the code for consistent code style and cells which do not exceed display length in the documentation.

Screenshot from 2021-02-24 23-05-47

### CODE REVIEW

**Review by pnkraemer — COMMENTED** [review]
Thanks for this! I like the changes, there is nothing to complain from my side. I have a few questions though
1) How did you turn those plots into the thumbnails? 
2) Any idea how we could enforce things like black on the notebooks as part of the CI? There is the issue of running the notebooks #295, can one also use black, isort (and even pylint?) for the notebooks?
3) While we're at it, have you tried isort on the notebooks too? Is it even possible? :thinking: 
4) I also (very slightly) prefer "ProbNum" over `probnum`. Is it in the styleguide that we'd like to refer to ProbNum in this way? If not, lets put it there.
5) Any changes other than the thumbnails and black? You wrote that you also changed a few other things (like headers?) but I cannot tell from comparing the appearance of the notebooks before and after.

**Comment by JonathanWenger** [comment]
> Thanks for this! I like the changes, there is nothing to complain from my side. I have a few questions though
> 
>     1. How did you turn those plots into the thumbnails?
See the guide on [how to create tutorial notebooks](https://probnum.readthedocs.io/en/latest/development/creating_an_example_notebook.html#Adding-the-Notebook-to-the-Website).
> 
>     2. Any idea how we could enforce things like black on the notebooks as part of the CI? There is the issue of running the notebooks #295, can one also use black, isort (and even pylint?) for the notebooks?
This is something I would really like to have, but have not researched how to yet. I put it on the agenda of the software meeting. Personally I use a `black` plugin for Jupyter.

>     3. While we're at it, have you tried isort on the notebooks too? Is it even possible? thinking
Have not tried.
>     4. I also (very slightly) prefer "ProbNum" over `probnum`. Is it in the styleguide that we'd like to refer to ProbNum in this way? If not, lets put it there.
[Yes it is there.](https://probnum.readthedocs.io/en/latest/development/styleguide.html#naming)
>     5. Any changes other than the thumbnails and black? You wrote that you also changed a few other things (like headers?) but I cannot tell from comparing the appearance of the notebooks before and after.
I have changed the notebook headers, since multiple top level headers (# Header) appear in the menu bar of the documentation as shown in the screenshot.

**Comment by pnkraemer** [comment]
> I have changed the notebook headers, since multiple top level headers (# Header) appear in the menu bar of the documentation as shown in the screenshot.

Ah I was looking in the diffeq tutorials, not in the filtering ones. My bad. Thanks for the fix.

**Review by pnkraemer — APPROVED** [review]
Thanks! In my opinion, we can merge this now (unless you want to wait for Jonathan's review as well).

**Pull request merged**
