### PR TITLE
Make `quad` integration measures stateless 

### PR DESCRIPTION
**Pull request by mmahsereci**
# In a Nutshell
This PR removes the default rng from the `quad` integration measures. Further, some long overdue shape tests for the sample method of the measures are added.

# Detailed Description
na

# Related Issues
Closes #...

### CODE REVIEW

**Review by tskarvone — APPROVED** [review]
Looks good to me. As a user, I personally find it a bit annoying to have to provide an rng myself, but there is probably a good reason for this change.

**Comment by mmahsereci** [comment]
> Looks good to me. As a user, I personally find it a bit annoying to have to provide an rng myself, but there is probably a good reason for this change.

It's mostly in preparation for #581 . See https://github.com/probabilistic-numerics/probnum/pull/744#discussion_r1031119249

**Comment by mmahsereci** [comment]
The tox docs build seems to have failed when merging into `main`. I am not reverting though as the RTD build seems fine. Don't have time too look into it right away unfortunately. pinging @JonathanWenger for info.

**Comment by JonathanWenger** [comment]
@mmahsereci Should be fixed now in #754 .

**Pull request merged**
