### PR TITLE
ODE solution sampling fixed

### PR DESCRIPTION
**Pull request by pnkraemer**
The previous samples were ``too smooth''. Now, this is fixed:
Screenshot from 2020-10-19 15-40-35

### CODE REVIEW

**Review by nathanaelbosch — CHANGES_REQUESTED** [review]
Good work on fixing that :) Once the CI checks pass I'm fine with merging.

**Review by nathanaelbosch — CHANGES_REQUESTED** [review]
Looks good, but the documentation build seems to fail.

**Comment by pnkraemer** [comment]
any idea why? I have no clue.

**Comment by nathanaelbosch** [comment]
> any idea why? I have no clue.

No idea :/

**Comment by pnkraemer** [comment]
> > any idea why? I have no clue.
> 
> No idea :/

One of the notebooks was referenced under the wrong name.

**Review by nathanaelbosch — APPROVED** [review]

**Pull request merged**
